spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:startup.sql';
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console